### ISSUE TITLE
[cssz] flaky výkon

### ISSUE THREAD

**Issue by kokes** [kokes/od#142]
Různě to erroruje na různých krocích - těžko říct, kde je chyba... možná je čas zaverzovat ten přehled URLs (a připravit bokem skript, který ho aktualizuje).

**Comment by jindroush** [comment]
Je to tento error? Mně to pravidelně končí na it72
```

cssz
====
72it [00:28,  2.49it/s]
Traceback (most recent call last):
  File "E:\projekty\2022_04_21_statni_data2\od\main.py", line 86, in <module>
    module(outdir, partial=args.partial)
  File "E:\projekty\2022_04_21_statni_data2\od\data\cssz\main.py", line 41, in main
    scha = najdi_textem(dht, "a", "Schéma (JSON)")
  File "E:\projekty\2022_04_21_statni_data2\od\data\cssz\main.py", line 20, in najdi_textem
    assert len(els) == 1, els
AssertionError: []
```
