### ISSUE TITLE
[zakazky] Rozbité zpracování ODZZVZ (2021)

### ISSUE THREAD

**Issue by kokes** [kokes/od#166]
Nalezeno v rámci #162. Vypadá to na chybějící schéma souboru.

```
Necekane dlouha radka (1. v https://isvz.nipez.cz/sites/default/files/content/opendata-predchozi/ODZZVZ/2021.csv)
Necekane dlouha radka (2. v https://isvz.nipez.cz/sites/default/files/content/opendata-predchozi/ODZZVZ/2021.csv)
Necekane dlouha radka (3. v https://isvz.nipez.cz/sites/default/files/content/opendata-predchozi/ODZZVZ/2021.csv)
Necekane dlouha radka (4. v https://isvz.nipez.cz/sites/default/files/content/opendata-predchozi/ODZZVZ/2021.csv)
Necekane dlouha radka (5. v https://isvz.nipez.cz/sites/default/files/content/opendata-predchozi/ODZZVZ/2021.csv)
...
Necekane dlouha radka (285. v https://isvz.nipez.cz/sites/default/files/content/opendata-predchozi/ODZZVZ/2021.csv)
Necekane dlouha radka (286. v https://isvz.nipez.cz/sites/default/files/content/opendata-predchozi/ODZZVZ/2021.csv)
Necekane dlouha radka (287. v https://isvz.nipez.cz/sites/default/files/content/opendata-predchozi/ODZZVZ/2021.csv)
Traceback (most recent call last):
  File "/Users/okokes/git/od/main.py", line 86, in <module>
    module(outdir, partial=args.partial)
  File "/Users/okokes/git/od/data/zakazky/main.py", line 166, in main
    ln[cln] = fix_date(ln[cln])
  File "/Users/okokes/git/od/data/zakazky/main.py", line 50, in fix_date
    return datetime.strptime(s, "%d.%m.%Y %H:%M:%S").isoformat()
  File "/Users/okokes/.pyenv/versions/3.9.0/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/Users/okokes/.pyenv/versions/3.9.0/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'TRUE' does not match format '%d.%m.%Y %H:%M:%S'
```

**Comment by jindroush** [comment]
Jsem si v té funkci fix_date udělal ještě toto:
```
        try:
            fixed = datetime.strptime(s, "%d.%m.%Y %H:%M:%S").isoformat()
        except:
            fixed = None
        return fixed

```
aby to nevybombilo (překvapilo mě, že to TRUE proleze přes     if isodate.match(s) is not None:), ale stejně to zase zdechne v tom fix_numeric. Já vím, že to tam proleze, jen proto, že je to nějaký rozbitý, ale i tak.

Jinak bych navrhoval vyhazovat ve fix_ico i všelijaký interpunkční znaménka - tečky, čárky, středníky jsem viděl na konci docela často.

**Comment by kokes** [comment]
To datum jsem zatím nezkoumal, ale co se týče té nečekaně dlouhé řádky, oni mají chybu v tom, že na konci prvních pár set řádků (minimálně, možná všude) dávají středník, který tam nepatří. Naznačují tak o sloupec více, pro který nemají hodnotu ve hlavičce.

2021:

```
$ curl -s https://isvz.nipez.cz/sites/default/files/content/opendata-predchozi/ODZZVZ/2021.csv | head -4
"Přehled zakázek na formulářích z Věstníku VZ pro zákon 134 2016 Sb. (mimo formuláře F16-F19)"

"ID_Zakazky";"EvidencniCisloVZnaVVZ";"CisloFormulareNaVVZ";"DruhFormulare";"ID_Zadani";"CisloCastiZadaniVZ";"NazevCastiVZ";"ZadaniCastiZakazky";"InformaceONezadaniCastiZakazky";"DatumZadaniVZ";"PocetObdrzenychNabidek";"PuvodniOdhadovanaCelkovaHodnotaVZ";"PuvodniOdhadovanaCelkovaHodnotaVZMena";"CelkovaKonecnaHodnotaVZzaZadani";"CelkovaKonecnaHodnotaVZmenaZaZadani";"HodnotaNejnizsiNabidky";"HodnotaNejnizsiNabidkyMena";"HodnotaNejvyssiNabidky";"SubdodavkyHodnotaBezDPH";"SubdodavkyMena";"SubdodavkyPomer";"DatumOdeslaniFormulareNaVVZ";"PlatnyFormular"
"2024997";"Z2021-000054";"F2021-000054";"CZ03";"2489033";"";"Obnova lesních průseků na ropovodu Družba a IKL";"Ne";"Ukonceni rizeni";"";"";"";"";"";"CZK";"";"";"";"";"";"";"2021-01-04";"TRUE";
```

2020:

```
$ curl -s https://isvz.nipez.cz/sites/default/files/content/opendata-predchozi/ODZZVZ/2020.csv | head -4
"Přehled zakázek na formulářích z Věstníku VZ pro zákon 134 2016 Sb. (mimo formuláře F16-F19)"

"ID_Zakazky";"EvidencniCisloVZnaVVZ";"CisloFormulareNaVVZ";"DruhFormulare";"ID_Zadani";"CisloCastiZadaniVZ";"NazevCastiVZ";"ZadaniCastiZakazky";"InformaceONezadaniCastiZakazky";"DatumZadaniVZ";"PocetObdrzenychNabidek";"PuvodniOdhadovanaCelkovaHodnotaVZ";"PuvodniOdhadovanaCelkovaHodnotaVZMena";"CelkovaKonecnaHodnotaVZzaZadani";"CelkovaKonecnaHodnotaVZmenaZaZadani";"HodnotaNejnizsiNabidky";"HodnotaNejnizsiNabidkyMena";"HodnotaNejvyssiNabidky";"SubdodavkyHodnotaBezDPH";"SubdodavkyMena";"SubdodavkyPomer";"DatumOdeslaniFormulareNaVVZ";"PlatnyFormular"
665c3bb5-a947-45d6-b81c-0089fea6d900;"Z2020-045989";"F2020-045989";"CZ03";cd0e39a7-7143-49f6-8aa8-a551563f158f;;;"Ano";;17.12.2020 0:00:00;;;;5000000,00;"CZK";;;;;;;22.12.2020 0:00:00;False
```

**Comment by kokes** [comment]
A co se týče toho data - tak to není chyba na mé straně - ono totiž TRUE opravdu není datum, my se ho snažíme naparsovat, protože v datech je chyba - nejsou to validní CSV soubory, takže parsujeme špatný sloupec. Tuto chybu jsem MMR nahlásil 17. ledna letošního roku, ale do dnes se jim to nepodařilo opravit.

**Comment by kokes** [comment]
Pokud mě MMR bude dál ignorovat, budem muset přejít na XML.
